characteristics.py for audio waveform characteristics
Glassmasters/BirdCLEF_Glassmasters pull request #26
Opened 2023-04-23 20:10 UTC by MarionHinkel

#13 
added audio waveform characteristics for
- maximum
- minimum
- mean
- std
- fft
- to db
- envelope
- percentile

2023-04-24 13:06 UTC, Flippchen commented on src/preprocess/waveform_characteristics/characteristics.py
> +    min_value = torch.min(torch.abs(audio_data))
```suggestion
    min_value = torch.min(audio_data)
```

2023-04-24 13:06 UTC, Flippchen commented on src/preprocess/waveform_characteristics/characteristics.py
> +    db_value = 20 * torch.log10(torch.abs(audio_data))
```suggestion
    eps = 1e-12 #constant to avoid zero in log
    db_value = 20 * torch.log10(torch.abs(audio_data) + eps)
```

2023-04-24 13:06 UTC, Flippchen commented on src/preprocess/waveform_characteristics/characteristics.py
> +    rectified_signal = relu(audio_data)
```suggestion
    rectified_signal = torch.abs(audio_data)
```

2023-04-24 13:06 UTC, Flippchen commented on src/preprocess/waveform_characteristics/characteristics.py
> +    percentile_value = torch.quantile(audio_data, percentile / 100)
```suggestion
    percentile_value = torch.quantile(audio_data, percentile / 100.0)
```

2023-04-24 16:25 UTC, anwielts commented on src/preprocess/waveform_characteristics/characteristics.py
> +    rectified_signal = relu(audio_data)
@Flippchen : Absolute values are in view not the same as the envelope. @MarionHinkel Maybe have a look here: https://stackoverflow.com/questions/37968221/how-to-get-and-plot-a-signal-envelope

2023-04-24 16:28 UTC, anwielts requested changes
Only thing missing/needs to be changed is the envelope claculation. Everything else looks good

2023-04-26 16:11 UTC, Flippchen commented on src/preprocess/waveform_characteristics/characteristics.py
> +    Calculates the envelope of an audio waveform using PyTorch.
Outdated docstring?

2023-04-26 16:12 UTC, anwielts approved these changes
LGTM

2023-04-26 16:26 UTC, MarionHinkel commented on src/preprocess/waveform_characteristics/characteristics.py
> +    Calculates the envelope of an audio waveform using PyTorch.
you are right

2023-04-26 16:26 UTC, Flippchen approved these changes
LGTM

2023-04-26 16:28 UTC, merged